name: Auto Merge Daily Branch

on:
  schedule:
    - cron: "30 23 * * *"
  workflow_dispatch:

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current datetime as env variable
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create a new branch and commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b batch/${{ env.CURRENT_DATETIME }}
          # Add your commands to update the repository content here
          git commit --allow-empty -m "chore: Update database on ${{ env.CURRENT_DATETIME }}"
          git push origin batch/${{ env.CURRENT_DATETIME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        id: create_pr
        run: |
          PR_URL=$(gh pr create \
            --base main \
            --head batch/${{ env.CURRENT_DATETIME }} \
            --title "chore: Update database on ${{ env.CURRENT_DATETIME }}" \
            --body "This pull request merges the branch batch/${{ env.CURRENT_DATETIME }} into main." \
            --assignee ryohidaka \
            --reviewer ryohidaka)
          echo "PR_URL=${PR_URL}" >> $GITHUB_ENV

      - name: Merge pull request
        if: env.PR_URL != ''
        run: |
          PR_NUMBER=$(echo "${{ env.PR_URL }}" | grep -oE '[0-9]+$')
          gh pr merge $PR_NUMBER --squash --admin --delete-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
