name: Auto Merge Daily Branch

on:
  schedule:
    - cron: "50 23 * * *"
  workflow_dispatch:

jobs:
  create-and-merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current datetime as env variable
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Merge pull request
        run: |
          PR_NUMBER=$(gh pr list --base main --head batch/${{ env.CURRENT_DATETIME }} --json number -q '.[0].number')
          if [ -n "$PR_NUMBER" ]; then
            gh pr merge $PR_NUMBER --squash --admin --delete-branch
          else
            echo "No PR found from test to main."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
