name: Create Daily Branch

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  create-daily-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current datetime as env variable
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create and checkout batch branch
        run: |
          git switch -c batch/${{ env.CURRENT_DATETIME }}
          git push origin HEAD
