name: Create Daily Branch

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  create-daily-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current datetime as env variable
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create and checkout batch branch
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git switch -c batch/${{ env.CURRENT_DATETIME }}
          
          git commit --allow-empty -m "chore: Update database on ${{ env.CURRENT_DATETIME }}"
          git push origin HEAD

      - name: Create pull request
        run: |
          gh pr create \
            --base main \
            --head batch/${{ env.CURRENT_DATETIME }} \
            --title "chore: Update database on ${{ env.CURRENT_DATETIME }}" \
            --body "This pull request merges the branch batch/${{ env.CURRENT_DATETIME }} into main." \
            --assignee ryohidaka \
            --reviewer ryohidaka
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
