name: Export JSON

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - "db/**"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Dumpfile
        run: cat db/x* > db/dump.sql

      - name: Restore DB
        uses: ryohidaka/action-restore-sqlite@v0.1.0
        with:
          db: "db/archives.db"
          dump-file: "db/dump.sql"

      - uses: actions/setup-go@v5
        with:
          go-version: "^1.21.3"
          check-latest: true
          cache-dependency-path: |
            src/export-json/go.sum

      - name: Export JSON
        run: cd src/export-json && go run cmd/main.go

      - name: Set current datetime as env variable
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: ryohidaka/action-commit-push@v0.5.0
        with:
          files: "json"
          commit-message: "chore: Update json on ${{ env.CURRENT_DATETIME }}"
